# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3689b92b81621b8c60f5464a8df0a4cdf960b3e95fd9db9ffdf3e497871bc146a99a9de7f025104f6d0a657de8b016eac1e7e82a2e52304494c56fee16467ac4

test:
  secret_key_base: 3e9a9f0a495da6300231e92c2961791e61d4c32f20a0d471deafecabbbeab9a06d658915d2ec88b21c874ea93eb81ef96d243569309cfdaf83ebbed163446147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
